# docker run -d -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -e "xpack.security.enabled=false" -e "xpack.monitoring.enabled=false" -e "xpack.watcher.enabled=false" -e "xpack.graph.enabled=false" -e "xpack.ml.enabled=false" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -p 9200:9200 -p 9300:9300 --name elasticsearch --network="elasticsearch" docker.elastic.co/elasticsearch/elasticsearch:5.4.1

# docker run -d --name kibana -p 5601:5601 -e "ELASTICSEARCH_URL=http://elasticsearch:9200" -e "xpack.graph.enabled=false" -e "xpack.security.enabled=false" -e "xpack.ml.enabled=false" --network="elasticsearch" docker.elastic.co/kibana/kibana:5.4.1



elasticsearch:
  container_name: elasticsearch
  build: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
    - "xpack.security.enabled=false"
    - "xpack.monitoring.enabled=false"
    - "xpack.watcher.enabled=false"
    - "xpack.graph.enabled=false"
    - "xpack.ml.enabled=false"
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

kibana:
  image: docker.elastic.co/kibana/kibana:5.4.1
  container_name: kibana
  ports:
    - "5601:5601"
  environment:
    # - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    - "xpack.graph.enabled=false"
    - "xpack.security.enabled=false"
    - "xpack.ml.enabled=false"
  links:
    - elasticsearch


# logstash:
#   image: docker.elastic.co/logstash/logstash:${VERSION_TAG}
#   links:
#     - elasticsearch
#     - redis
#   ports:
#     # Beats input -- https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-beats.html
#     - '5044:5044'
#     # UDP input -- https://www.elastic.co/guide/en/logstash/master/plugins-inputs-udp.html#plugins-inputs-udp-codec
#     - '43448:43448/udp'

#     # Monitoring APIs -- https://www.elastic.co/guide/en/logstash/5.0/monitoring.html
#     - '9600:9600'
# redis:
#   image: redis
#   ports: [ '6379:6379' ]