FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.1

RUN elasticsearch-plugin  install analysis-kuromoji
RUN elasticsearch-plugin install org.codelibs:elasticsearch-analysis-kuromoji-neologd:5.3.0
